ich möchte hier matrixmultiplikation von höherdimensionalen matrizen testen.

In [1]:
import torch

Erstellen einer normalen matrix und eines vektors zur multiplikation

In [2]:
vec = torch.tensor([1, 1, 1])
vec = vec.view((-1, 1))
print('Vektor: \n', vec)

matrix = torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print('Matrix: \n', matrix)

print('Matrix * Vektor: \n', torch.matmul(matrix, vec))
print('Matrix * Vektor Shape: \n', torch.matmul(matrix, vec).shape)

Vektor: 
 tensor([[1],
        [1],
        [1]])
Matrix: 
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
Matrix * Vektor: 
 tensor([[6],
        [6],
        [6]])
Matrix * Vektor Shape: 
 torch.Size([3, 1])


Nun mit einem Tensor höherer Stufe

In [3]:
vec_1 = torch.tensor([1, 1, 1])
print('Vektor: \n', vec_1)
print('Vektor Shape: ', vec_1.shape)

matrix_1 = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]]])
print('Matrix: \n', matrix_1)
print('Matrix Shape: ', matrix_1.shape)

erg = torch.matmul(matrix_1, vec_1)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)


Vektor: 
 tensor([1, 1, 1])
Vektor Shape:  torch.Size([3])
Matrix: 
 tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 2],
         [1, 2, 2],
         [1, 2, 2]]])
Matrix Shape:  torch.Size([2, 3, 3])
Matrix * Vektor: 
 tensor([[6, 6, 6],
        [5, 5, 5]])
Shape:  torch.Size([2, 3])


In [4]:
vec_2 = torch.tensor([[1, 1], [0, 0]])
vec_2 = vec_2.view(2, 1, -1, 1)
print('Vektor: \n', vec_2)
print('Vektor Shape: ', vec_2.shape)

matrix_2 = torch.tensor([[[[1, 2], [2, 3], [3, 4]], [[1, 2], [2, 3], [3, 4]], [[1, 2], [2, 3], [3, 4]]], [[[1, 2], [2, 3], [3, 4]], [[1, 2], [2, 3], [3, 4]], [[1, 2], [2, 3], [3, 4]]]])
print('Matrix: \n', matrix_2)
print('Matrix Shape: ', matrix_2.shape)

erg = torch.matmul(matrix_2, vec_2)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)


Vektor: 
 tensor([[[[1],
          [1]]],


        [[[0],
          [0]]]])
Vektor Shape:  torch.Size([2, 1, 2, 1])
Matrix: 
 tensor([[[[1, 2],
          [2, 3],
          [3, 4]],

         [[1, 2],
          [2, 3],
          [3, 4]],

         [[1, 2],
          [2, 3],
          [3, 4]]],


        [[[1, 2],
          [2, 3],
          [3, 4]],

         [[1, 2],
          [2, 3],
          [3, 4]],

         [[1, 2],
          [2, 3],
          [3, 4]]]])
Matrix Shape:  torch.Size([2, 3, 3, 2])
Matrix * Vektor: 
 tensor([[[[3],
          [5],
          [7]],

         [[3],
          [5],
          [7]],

         [[3],
          [5],
          [7]]],


        [[[0],
          [0],
          [0]],

         [[0],
          [0],
          [0]],

         [[0],
          [0],
          [0]]]])
Shape:  torch.Size([2, 3, 3, 1])


Test wie eine elemetnweise multiplikation funktioniert

In [7]:
test_qd = torch.tensor([[1, 1], [0, 0], [1, 1]], dtype=torch.float32)
d = torch.tensor([1, 2], dtype=torch.float32)

print('Elementweise Multiplikation: \n', test_qd*d)

Elementweise Multiplikation: 
 tensor([[1., 2.],
        [0., 0.],
        [1., 2.]])
