In diesem Jupyter Notebook werde ich mich mit Tests rundum die reshape funktion beschäftigen.

In [1]:
import numpy as np
import torch

Arrays definieren und ausgeben

In [4]:
arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([[1, 2], [3, 4]])
arr_c = np.array([[1, 2], [3, 4,]])
arr_d = np.array([[1, 2, 3, 4]])

print('Array a: \n', arr_a)
print('Array b: \n', arr_b)
print('Array c: \n', arr_c)
print('Array d: \n', arr_d)

Array a: 
 [1 2 3 4]
Array b: 
 [[1 2]
 [3 4]]
Array c: 
 [[1 2]
 [3 4]]
Array d: 
 [[1 2 3 4]]


Reshape Operationen ausführen (Array a)

In [7]:
print('Shape von Array a:', arr_a.shape)
print('Array gereshaped (-1, 1): \n', arr_a.reshape((-1, 1)))
print('Array gereshaped (1, -1): \n', arr_a.reshape((1, -1)))

Shape von Array a: (4,)
Array gereshaped (-1, 1): 
 [[1]
 [2]
 [3]
 [4]]
Array gereshaped (1, -1): 
 [[1 2 3 4]]


Rehape Operationen ausführen (Array b)

In [14]:
print('Shape von Array b:', arr_b.shape)
print('Array gereshaped (-1,): \n', arr_b.reshape((-1, )))
print('Array gereshaped (-1, 1): \n', arr_b.reshape((-1, 1)))
print('Array gereshaped (-1, 2): \n', arr_b.reshape((-1, 2)))

Shape von Array b: (2, 2)
Array gereshaped (-1,): 
 [1 2 3 4]
Array gereshaped (-1, 1): 
 [[1]
 [2]
 [3]
 [4]]
Array gereshaped (-1, 2): 
 [[1 2]
 [3 4]]


Torch Tensor definieren

In [16]:
arr_e = torch.asarray([1, 2, 3, 4])
print('Array e: \n', arr_e)

Array e: 
 tensor([1, 2, 3, 4])


Reshape Operationen ausführen (view bei torch)

In [21]:
print('Shape von Tensor:', arr_e.size())
print('Tensor view(-1, 2): \n', arr_e.view((-1, 2)))
print('Tensor view(-1, 1): \n', arr_e.view((-1, 1)))

Shape von Tensor: torch.Size([4])
Tensor view(-1, 2): 
 tensor([[1, 2],
        [3, 4]])
Tensor view(-1, 1): 
 tensor([[1],
        [2],
        [3],
        [4]])
