ich möchte hier matrixmultiplikation von höherdimensionalen matrizen testen.

In [5]:
import torch

Erstellen einer normalen matrix und eines vektors zur multiplikation

In [14]:
vec = torch.tensor([1, 1, 1])
vec = vec.view((-1, 1))
print('Vektor: \n', vec)

matrix = torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print('Matrix: \n', matrix)

print('Matrix * Vektor: \n', torch.matmul(matrix, vec))
print('Matrix * Vektor Shape: \n', torch.matmul(matrix, vec).shape)

Vektor: 
 tensor([[1],
        [1],
        [1]])
Matrix: 
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
Matrix * Vektor: 
 tensor([[6],
        [6],
        [6]])
Matrix * Vektor Shape: 
 torch.Size([3, 1])


Nun mit einem Tensor höherer Stufe

In [7]:
vec_1 = torch.tensor([1, 1, 1])
print('Vektor: \n', vec_1)
print('Vektor Shape: ', vec_1.shape)

matrix_1 = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]]])
print('Matrix: \n', matrix_1)
print('Matrix Shape: ', matrix_1.shape)

erg = torch.matmul(matrix_1, vec_1)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)


Vektor: 
 tensor([1, 1, 1])
Vektor Shape:  torch.Size([3])
Matrix: 
 tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 2],
         [1, 2, 2],
         [1, 2, 2]]])
Matrix Shape:  torch.Size([2, 3, 3])
Matrix * Vektor: 
 tensor([[6, 6, 6],
        [5, 5, 5]])
Shape:  torch.Size([2, 3])


In [18]:
vec_2 = torch.tensor([1, 1, 1])
vec_2 = vec_2.view(1, -1, 1)
print('Vektor: \n', vec_2)
print('Vektor Shape: ', vec_2.shape)

matrix_2 = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]]])
print('Matrix: \n', matrix_2)
print('Matrix Shape: ', matrix_2.shape)

erg = torch.matmul(matrix_2, vec_2)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)


Vektor: 
 tensor([[[1],
         [1],
         [1]]])
Vektor Shape:  torch.Size([1, 3, 1])
Matrix: 
 tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 2],
         [1, 2, 2],
         [1, 2, 2]]])
Matrix Shape:  torch.Size([2, 3, 3])
Matrix * Vektor: 
 tensor([[[6],
         [6],
         [6]],

        [[5],
         [5],
         [5]]])
Shape:  torch.Size([2, 3, 1])
