In [14]:
import torch

Nutzung von Einsum (einsteinsche Summenkonvention)

In [15]:
# Matrixmultiplikation
mat = torch.tensor([[1, 2], [0, 0]])
print('Vektor: \n', mat)
print('Vektor Shape: ', mat.shape)

matrix = torch.tensor([[1, 0], [0, 1]])
print('Vektor: \n', matrix)
print('Vektor Shape: ', matrix.shape)

erg = torch.einsum('ij,jk->ik', matrix, mat)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)

Vektor: 
 tensor([[1, 2],
        [0, 0]])
Vektor Shape:  torch.Size([2, 2])
Vektor: 
 tensor([[1, 0],
        [0, 1]])
Vektor Shape:  torch.Size([2, 2])
Matrix * Vektor: 
 tensor([[1, 2],
        [0, 0]])
Shape:  torch.Size([2, 2])


In [16]:
# Batch Matrixmultiplikation
mat = torch.tensor([[[1, 2], [0, 0]], [[0, 0], [1, 2]]])
print('Vektor: \n', mat)
print('Vektor Shape: ', mat.shape)

matrix = torch.tensor([[[1, 0], [0, 1]], [[1, 0], [0, 1]]])
print('Vektor: \n', matrix)
print('Vektor Shape: ', matrix.shape)

erg = torch.einsum('bij,bjk->bik', matrix, mat)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)

Vektor: 
 tensor([[[1, 2],
         [0, 0]],

        [[0, 0],
         [1, 2]]])
Vektor Shape:  torch.Size([2, 2, 2])
Vektor: 
 tensor([[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]])
Vektor Shape:  torch.Size([2, 2, 2])
Matrix * Vektor: 
 tensor([[[1, 2],
         [0, 0]],

        [[0, 0],
         [1, 2]]])
Shape:  torch.Size([2, 2, 2])


In [17]:
# Batch Matrixmultiplikation (wenn nur eine matrix als batch vorliegt)
mat = torch.tensor([[1, 2], [0, 0]])
print('Vektor: \n', mat)
print('Vektor Shape: ', mat.shape)

matrix = torch.tensor([[[1, 0], [0, 1]], [[1, 0], [0, 1]]])
print('Vektor: \n', matrix)
print('Vektor Shape: ', matrix.shape)

erg = torch.einsum('bij,jk->bik', matrix, mat)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)

Vektor: 
 tensor([[1, 2],
        [0, 0]])
Vektor Shape:  torch.Size([2, 2])
Vektor: 
 tensor([[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]])
Vektor Shape:  torch.Size([2, 2, 2])
Matrix * Vektor: 
 tensor([[[1, 2],
         [0, 0]],

        [[1, 2],
         [0, 0]]])
Shape:  torch.Size([2, 2, 2])


In [19]:
# DeLaN L_dt berechnen (L_dq * qd)
mat = torch.tensor([[1, 1],
                    [0, 0]])
print('Vektor: \n', mat)
print('Vektor Shape: ', mat.shape)

matrix = torch.tensor([[[[1, 1], [1, 1], [1, 1]], [[0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0]]],
                    [[[1, 1], [1, 1], [1, 1]], [[0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0]]]])
print('Vektor: \n', matrix)
print('Vektor Shape: ', matrix.shape)

erg = torch.einsum('bijk,bk->bij', matrix, mat)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)

Vektor: 
 tensor([[1, 1],
        [0, 0]])
Vektor Shape:  torch.Size([2, 2])
Vektor: 
 tensor([[[[1, 1],
          [1, 1],
          [1, 1]],

         [[0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0]]],


        [[[1, 1],
          [1, 1],
          [1, 1]],

         [[0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0]]]])
Vektor Shape:  torch.Size([2, 3, 3, 2])
Matrix * Vektor: 
 tensor([[[2, 2, 2],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
Shape:  torch.Size([2, 3, 3])


In [24]:
# DeLaN H_dq berechnen (L_dq * LT + ...)
mat = torch.tensor([[[1, 2, 3], [1, 1, 1], [0, 0, 0]],
                    [[0, 0, 0], [1, 1, 1], [0, 0, 0]]])
print('Vektor: \n', mat)
print('Vektor Shape: ', mat.shape)

matrix = torch.tensor([[[[1, 2], [1, 2], [1, 2]], [[0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0]]],
                    [[[0, 0], [0, 0], [0, 0]], [[1, 2], [1, 2], [1, 2]], [[0, 0], [0, 0], [0, 0]]]])
print('Vektor: \n', matrix)
print('Vektor Shape: ', matrix.shape)

erg = torch.einsum('bijc,bjk->bikc', matrix, mat)
print('Matrix * Vektor: \n', erg)
print('Shape: ', erg.shape)

Vektor: 
 tensor([[[1, 2, 3],
         [1, 1, 1],
         [0, 0, 0]],

        [[0, 0, 0],
         [1, 1, 1],
         [0, 0, 0]]])
Vektor Shape:  torch.Size([2, 3, 3])
Vektor: 
 tensor([[[[1, 2],
          [1, 2],
          [1, 2]],

         [[0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0]],

         [[1, 2],
          [1, 2],
          [1, 2]],

         [[0, 0],
          [0, 0],
          [0, 0]]]])
Vektor Shape:  torch.Size([2, 3, 3, 2])
Matrix * Vektor: 
 tensor([[[[2, 4],
          [3, 6],
          [4, 8]],

         [[0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0]],

         [[1, 2],
          [1, 2],
          [1, 2]],

         [[0, 0],
          [0, 0],
          [0, 0]]]])
Shape:  torch.Size([2, 3, 3, 2])
